//! Chat conversation view — supports both plain text replies and structured
//! "cowork" replies with collapsible tool-call blocks and **streaming**
//! Markdown bodies (rendered via `TextView` + `TextViewState`). Mock data
//! mirrors the layout captured in `demo.html`.
use gpui::prelude::FluentBuilder as _;
use gpui::{
    AnyElement, Context, Div, Entity, Hsla, InteractiveElement as _, IntoElement, ObjectFit,
    ParentElement as _, ScrollAnchor, SharedString, StatefulInteractiveElement as _, Styled,
    StyledImage as _, Window, div, hsla, img, linear_color_stop, linear_gradient, px, relative,
};
use gpui_component::{
    Icon, IconName, WindowExt as _, h_flex,
    notification::Notification,
    scroll::ScrollableElement as _,
    text::{TextView, TextViewState},
    tooltip::Tooltip,
    v_flex,
};
use std::collections::HashMap;
use std::path::PathBuf;

use crate::models::{BranchOrigin, TokenUsageStats};
use crate::theme::{
    accent, border_color, file_chip_bg, file_chip_hover_bg, hover_bg, text_2, text_3, text_color,
    timeline_line, user_bubble_bg, white_color,
};
use crate::{ChatMessage, ChatMode, ChatRole};

pub trait ChatViewState: Sized + 'static {
    fn messages(&self) -> &[ChatMessage];
    fn cowork_user_expanded(&self) -> &[bool];
    fn tool_expanded(&self) -> &HashMap<(usize, usize), bool>;
    fn pending(&self) -> bool;
    fn mode(&self) -> ChatMode;
    fn branch_origin(&self) -> Option<&BranchOrigin>;
    fn highlighted_artifact_target(&self) -> Option<ArtifactHighlightTarget> {
        None
    }
    fn message_scroll_anchor(&self, _ix: usize) -> Option<ScrollAnchor> {
        None
    }
    fn open_image_viewer(
        &self,
        image: ImageAttachment,
        window: &mut Window,
        cx: &mut Context<Self>,
    );
    fn reveal_file(&mut self, path: PathBuf, window: &mut Window, cx: &mut Context<Self>);
    fn copy_ai_message(&mut self, ix: usize, window: &mut Window, cx: &mut Context<Self>);
    fn branch_conversation_from_message(
        &mut self,
        ix: usize,
        window: &mut Window,
        cx: &mut Context<Self>,
    );
    fn open_branch_origin(
        &mut self,
        origin: BranchOrigin,
        window: &mut Window,
        cx: &mut Context<Self>,
    );
    fn delete_ai_message(&mut self, ix: usize, window: &mut Window, cx: &mut Context<Self>);
    fn regenerate_ai_message(&mut self, ix: usize, window: &mut Window, cx: &mut Context<Self>);
    fn copy_user_message(&mut self, ix: usize, window: &mut Window, cx: &mut Context<Self>);
    fn delete_user_message(&mut self, ix: usize, window: &mut Window, cx: &mut Context<Self>);
    fn edit_user_message(&mut self, ix: usize, window: &mut Window, cx: &mut Context<Self>);
    fn regenerate_from_user_message(
        &mut self,
        ix: usize,
        window: &mut Window,
        cx: &mut Context<Self>,
    );
    fn toggle_cowork_user_expanded(&mut self, ix: usize, cx: &mut Context<Self>);
    fn toggle_tool_expanded(&mut self, key: (usize, usize), cx: &mut Context<Self>);
    fn toggle_thinking_expanded(&mut self, key: (usize, usize), cx: &mut Context<Self>);
    fn open_thinking_viewer(
        &self,
        title: SharedString,
        state: Entity<TextViewState>,
        window: &mut Window,
        cx: &mut Context<Self>,
    );
}

/// Rich content block that an AI message can contain.
#[derive(Clone)]
pub enum MessageBlock {
    /// Streaming reasoning/thinking content rendered above the assistant answer.
    Thinking(ThinkingBlock),
    /// Streaming Markdown content rendered via `TextView`.
    Markdown(Entity<TextViewState>),
    /// Image generated by an image model or mock image-generation backend.
    GeneratedImage(GeneratedImage),
    /// Collapsible tool-invocation block.
    Tool(ToolCall),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct ArtifactHighlightTarget {
    pub(crate) message_ix: usize,
    pub(crate) kind: ArtifactHighlightKind,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ArtifactHighlightKind {
    Attachment { attachment_ix: usize },
    GeneratedImage { block_ix: usize },
    ToolFile { tool_ix: usize, step_ix: usize },
}

#[derive(Clone)]
pub struct ThinkingBlock {
    pub state: Entity<TextViewState>,
    pub done: bool,
    pub expanded: bool,
}

#[derive(Clone)]
pub struct ImageAttachment {
    pub title: SharedString,
    pub url: SharedString,
    pub detail: SharedString,
    pub path: Option<PathBuf>,
    pub parsed_text: Option<SharedString>,
    pub parse_error: Option<SharedString>,
}

impl ImageAttachment {
    pub(crate) fn is_document(&self) -> bool {
        self.parsed_text.is_some()
            || self.parse_error.is_some()
            || self
                .path
                .as_deref()
                .is_some_and(crate::document_parser::is_supported_document_path)
    }
}

#[derive(Clone)]
pub struct GeneratedImage {
    pub title: SharedString,
    pub prompt: SharedString,
    pub url: SharedString,
    pub size: SharedString,
}

#[derive(Clone)]
pub struct ToolCall {
    pub title: SharedString,
    pub steps: Vec<ToolStep>,
}

#[derive(Clone)]
pub struct ToolStep {
    pub icon: IconName,
    pub title: SharedString,
    pub detail: Option<SharedString>,
    /// Optional inline "file pill" rendered under the step title.
    pub file_chip: Option<SharedString>,
    /// Final "Done" step is rendered in a brighter accent color.
    pub done: bool,
}

/// Render the chat content area.
pub fn render<T: ChatViewState>(app: &T, cx: &mut Context<T>) -> impl IntoElement {
    let messages = app.messages().to_vec();
    let user_expanded = app.cowork_user_expanded().to_vec();
    let tool_expanded = app.tool_expanded().clone();
    let pending = app.pending();
    let branch_origin = app.branch_origin().cloned();
    let branch_insert_ix = branch_origin
        .as_ref()
        .map(|origin| origin.message_count.min(messages.len()));
    let has_streaming_message = pending
        && messages.last().is_some_and(|message| {
            message.role == ChatRole::Ai
                && (message
                    .blocks
                    .as_ref()
                    .is_some_and(|blocks| !blocks.is_empty())
                    || !message.content.is_empty()
                    || !message.thinking.is_empty())
        });
    let pending_mode = messages
        .iter()
        .rev()
        .find(|message| message.role == ChatRole::User)
        .map(|message| message.mode)
        .unwrap_or(app.mode());

    v_flex()
        .w_full()
        .max_w(px(760.))
        .px_5()
        .pt_4()
        .pb_4()
        .gap_6()
        .when(branch_insert_ix == Some(0), |this| {
            this.children(
                branch_origin
                    .clone()
                    .map(|origin| render_branch_origin_timeline(origin, cx)),
            )
        })
        .children(messages.into_iter().enumerate().flat_map(|(ix, m)| {
            let mut elements = Vec::with_capacity(2);
            let highlighted_artifact = app.highlighted_artifact_target();
            let scroll_anchor = app.message_scroll_anchor(ix);
            elements.push(match m.role {
                ChatRole::User => render_user_message(
                    ix,
                    &m,
                    user_expanded.get(ix).copied().unwrap_or(false),
                    highlighted_artifact,
                    scroll_anchor,
                    cx,
                )
                .into_any_element(),
                ChatRole::Ai => render_ai_message(
                    ix,
                    &m,
                    &tool_expanded,
                    highlighted_artifact,
                    scroll_anchor,
                    cx,
                )
                .into_any_element(),
            });

            if branch_insert_ix == Some(ix + 1) {
                if let Some(origin) = branch_origin.clone() {
                    elements.push(render_branch_origin_timeline(origin, cx).into_any_element());
                }
            }
            elements
        }))
        .when(pending && !has_streaming_message, |this| {
            this.child(render_thinking(pending_mode))
        })
}

fn render_branch_origin_timeline<T: ChatViewState>(
    origin: BranchOrigin,
    cx: &mut Context<T>,
) -> impl IntoElement {
    let title = if origin.source_title.as_ref().trim().is_empty() {
        crate::tr!("conversation.untitled")
    } else {
        origin.source_title.clone()
    };
    let origin_for_click = origin.clone();

    h_flex()
        .id(format!(
            "branch-origin-{}-{}",
            origin.source_conversation_id, origin.message_count
        ))
        .w_full()
        .items_center()
        .gap_2()
        .text_size(px(12.))
        .text_color(text_3())
        .child(div().h(px(1.)).flex_1().bg(timeline_line()))
        .child(
            h_flex()
                .items_center()
                .gap_1()
                .min_w_0()
                .child(crate::tr!("chat_view.branch_from"))
                .child(
                    div()
                        .id(format!(
                            "branch-origin-title-{}-{}",
                            origin.source_conversation_id, origin.message_count
                        ))
                        .max_w(px(320.))
                        .truncate()
                        .cursor_pointer()
                        .text_color(accent())
                        .hover(|this| this.text_color(text_color()))
                        .tooltip(|window, cx| {
                            Tooltip::new(crate::tr!("chat_view.open_source")).build(window, cx)
                        })
                        .child(title)
                        .on_click(cx.listener(move |this, _, window, cx| {
                            cx.stop_propagation();
                            this.open_branch_origin(origin_for_click.clone(), window, cx);
                        })),
                ),
        )
        .child(div().h(px(1.)).flex_1().bg(timeline_line()))
}

fn render_user_message<T: ChatViewState>(
    ix: usize,
    msg: &ChatMessage,
    expanded: bool,
    highlighted_artifact: Option<ArtifactHighlightTarget>,
    scroll_anchor: Option<ScrollAnchor>,
    cx: &mut Context<T>,
) -> impl IntoElement {
    let content = msg.content.clone();
    let long = content.chars().count() > 320;
    let bubble_bg = user_bubble_bg();
    let group_id = format!("user-message-{ix}");

    v_flex()
        .id(("chat-message", ix))
        .anchor_scroll(scroll_anchor)
        .group(group_id.clone())
        .items_end()
        .child(
            v_flex()
                .max_w(px(640.))
                .bg(bubble_bg)
                .text_color(text_color())
                .rounded_xl()
                .px_4()
                .py_3()
                .gap_2()
                .when(!msg.attachments.is_empty(), |this| {
                    this.child(render_user_attachments(
                        ix,
                        &msg.attachments,
                        highlighted_artifact,
                        cx,
                    ))
                })
                .when(!content.is_empty(), |this| {
                    this.child(
                        div()
                            .text_size(px(14.))
                            .line_height(relative(1.55))
                            .child(
                                TextView::markdown(format!("user-message-content-{ix}"), content)
                                    .selectable(true),
                            )
                            .when(long && !expanded, |this| {
                                this.h(px(170.)).overflow_hidden().relative().child(
                                    div()
                                        .absolute()
                                        .left_0()
                                        .right_0()
                                        .bottom_0()
                                        .h(px(24.))
                                        .bg(linear_gradient(
                                            180.,
                                            linear_color_stop(bubble_bg.opacity(0.0), 0.),
                                            linear_color_stop(bubble_bg.opacity(0.92), 1.),
                                        )),
                                )
                            }),
                    )
                })
                .when(long, |this| {
                    this.child(
                        div()
                            .id(("show-more", ix))
                            .text_size(px(12.))
                            .text_color(text_3())
                            .cursor_pointer()
                            .hover(|h| h.text_color(text_color()))
                            .child(if expanded {
                                crate::tr!("chat_view.show_less")
                            } else {
                                crate::tr!("chat_view.show_more")
                            })
                            .on_click(cx.listener(move |this, _, _, cx| {
                                this.toggle_cowork_user_expanded(ix, cx);
                            })),
                    )
                }),
        )
        .child(render_user_actions(ix, group_id, cx))
}

fn render_user_attachments<T: ChatViewState>(
    msg_ix: usize,
    attachments: &[ImageAttachment],
    highlighted_artifact: Option<ArtifactHighlightTarget>,
    cx: &mut Context<T>,
) -> Div {
    let mut row = h_flex().gap_2().flex_wrap();
    for (ix, attachment) in attachments.iter().enumerate() {
        let highlighted = highlighted_artifact.is_some_and(|target| {
            target.message_ix == msg_ix
                && target.kind == ArtifactHighlightKind::Attachment { attachment_ix: ix }
        });
        row = row.child(render_attachment_thumbnail(
            format!("user-image-{msg_ix}-{ix}"),
            attachment,
            px(142.),
            px(96.),
            highlighted,
            cx,
        ));
    }
    row
}

fn render_ai_message<T: ChatViewState>(
    ix: usize,
    msg: &ChatMessage,
    tool_expanded: &HashMap<(usize, usize), bool>,
    highlighted_artifact: Option<ArtifactHighlightTarget>,
    scroll_anchor: Option<ScrollAnchor>,
    cx: &mut Context<T>,
) -> impl IntoElement {
    let mode = msg.mode;
    let model = msg.model.clone();
    let token_stats = (mode == ChatMode::Chat)
        .then_some(msg.token_stats)
        .flatten();
    let header = h_flex()
        .gap_2()
        .items_center()
        .mb_2()
        .child(div().text_color(accent()).text_size(px(17.)).child("✳"))
        .child(
            h_flex()
                .gap_1p5()
                .items_center()
                .min_w_0()
                .child(
                    div()
                        .text_size(px(12.))
                        .text_color(text_3())
                        .truncate()
                        .child(crate::tr!(
                            "chat_view.message_header",
                            mode = crate::i18n::chat_mode_label(mode).to_string(),
                            model = model.to_string()
                        )),
                )
                .when_some(token_stats, |this, stats| {
                    this.child(metadata_chip(token_speed_label(stats), text_3()))
                }),
        );

    let body = if let Some(blocks) = &msg.blocks {
        render_blocks(ix, blocks, tool_expanded, highlighted_artifact, cx)
    } else {
        v_flex().gap_3().child(
            div()
                .max_w(px(680.))
                .px_3p5()
                .py_2p5()
                .rounded_xl()
                .rounded_bl(px(4.))
                .bg(white_color())
                .border_1()
                .border_color(border_color())
                .shadow_sm()
                .text_size(px(14.))
                .line_height(relative(1.55))
                .child(msg.content.clone()),
        )
    };
    let group_id = format!("ai-message-{ix}");

    div()
        .id(("chat-message", ix))
        .anchor_scroll(scroll_anchor)
        .child(
            v_flex()
                .group(group_id.clone())
                .items_start()
                .child(header)
                .child(body)
                .child(render_ai_actions(ix, group_id, cx)),
        )
}

fn token_speed_label(stats: TokenUsageStats) -> SharedString {
    let speed = if stats.tokens_per_second >= 100.0 {
        format!("{:.0}", stats.tokens_per_second)
    } else {
        format!("{:.1}", stats.tokens_per_second)
    };
    crate::tr!(
        "chat_view.token_speed",
        tokens = stats.output_tokens,
        speed = speed
    )
}

fn render_ai_actions<T: ChatViewState>(
    ix: usize,
    group_id: String,
    cx: &mut Context<T>,
) -> impl IntoElement {
    h_flex()
        .id(format!("ai-actions-{ix}"))
        .h(px(28.))
        .mt_1()
        .gap_1()
        .items_center()
        .text_color(text_2())
        .invisible()
        .group_hover(group_id, |this| this.visible())
        .child(ai_message_action(
            format!("copy-ai-message-{ix}"),
            IconName::Copy,
            crate::tr!("chat_view.copy"),
            move |this, window, cx| this.copy_ai_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("branch-ai-message-{ix}"),
            IconName::Network,
            crate::tr!("chat_view.branch"),
            move |this, window, cx| this.branch_conversation_from_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("delete-ai-message-{ix}"),
            IconName::Delete,
            crate::tr!("chat_view.delete"),
            move |this, window, cx| this.delete_ai_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("regenerate-ai-message-{ix}"),
            IconName::Redo2,
            crate::tr!("chat_view.regenerate"),
            move |this, window, cx| this.regenerate_ai_message(ix, window, cx),
            cx,
        ))
}

fn render_user_actions<T: ChatViewState>(
    ix: usize,
    group_id: String,
    cx: &mut Context<T>,
) -> impl IntoElement {
    h_flex()
        .id(format!("user-actions-{ix}"))
        .h(px(28.))
        .mt_1()
        .gap_1()
        .items_center()
        .text_color(text_2())
        .invisible()
        .group_hover(group_id, |this| this.visible())
        .child(ai_message_action(
            format!("copy-user-message-{ix}"),
            IconName::Copy,
            crate::tr!("chat_view.copy"),
            move |this, window, cx| this.copy_user_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("branch-user-message-{ix}"),
            IconName::Network,
            crate::tr!("chat_view.branch"),
            move |this, window, cx| this.branch_conversation_from_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("delete-user-message-{ix}"),
            IconName::Delete,
            crate::tr!("chat_view.delete"),
            move |this, window, cx| this.delete_user_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("edit-user-message-{ix}"),
            IconName::Replace,
            crate::tr!("chat_view.edit"),
            move |this, window, cx| this.edit_user_message(ix, window, cx),
            cx,
        ))
        .child(ai_message_action(
            format!("regenerate-from-user-message-{ix}"),
            IconName::Redo2,
            crate::tr!("chat_view.regenerate"),
            move |this, window, cx| this.regenerate_from_user_message(ix, window, cx),
            cx,
        ))
}

fn ai_message_action<T: ChatViewState>(
    id: String,
    icon: IconName,
    tooltip: SharedString,
    on_click: impl Fn(&mut T, &mut Window, &mut Context<T>) + 'static,
    cx: &mut Context<T>,
) -> impl IntoElement {
    div()
        .id(id)
        .size_7()
        .rounded_md()
        .flex()
        .items_center()
        .justify_center()
        .cursor_pointer()
        .text_color(text_2())
        .hover(|this| this.bg(hover_bg()).text_color(text_color()))
        .tooltip(move |window, cx| Tooltip::new(tooltip.clone()).build(window, cx))
        .child(Icon::new(icon).size_3p5())
        .on_click(cx.listener(move |this, _, window, cx| {
            cx.stop_propagation();
            on_click(this, window, cx);
        }))
}

fn render_blocks<T: ChatViewState>(
    msg_ix: usize,
    blocks: &[MessageBlock],
    tool_expanded: &HashMap<(usize, usize), bool>,
    highlighted_artifact: Option<ArtifactHighlightTarget>,
    cx: &mut Context<T>,
) -> Div {
    let mut col = v_flex().gap_3().w_full().max_w(px(700.));
    for (ix, block) in blocks.iter().enumerate() {
        let el: AnyElement = match block {
            MessageBlock::Thinking(thinking) => {
                render_thinking_block(msg_ix, ix, thinking, cx).into_any_element()
            }
            MessageBlock::Markdown(state) => div()
                .w_full()
                .text_size(px(14.5))
                .line_height(relative(1.7))
                .text_color(text_color())
                .child(TextView::new(state).selectable(true))
                .into_any_element(),
            MessageBlock::GeneratedImage(image) => {
                let highlighted = highlighted_artifact.is_some_and(|target| {
                    target.message_ix == msg_ix
                        && target.kind == ArtifactHighlightKind::GeneratedImage { block_ix: ix }
                });
                render_generated_image(msg_ix, ix, image, highlighted, cx).into_any_element()
            }
            MessageBlock::Tool(tc) => {
                let expanded = tool_expanded.get(&(msg_ix, ix)).copied().unwrap_or(true);
                render_tool_call(msg_ix, ix, tc, expanded, highlighted_artifact, cx)
                    .into_any_element()
            }
        };
        col = col.child(el);
    }
    div().child(col)
}

fn render_thinking_block<T: ChatViewState>(
    msg_ix: usize,
    block_ix: usize,
    thinking: &ThinkingBlock,
    cx: &mut Context<T>,
) -> impl IntoElement {
    let expanded = thinking.expanded || !thinking.done;
    let title = if thinking.done {
        crate::tr!("chat_view.thoughts")
    } else {
        crate::tr!("chat_view.thinking")
    };
    let chevron_rotation: f32 = if expanded { 0.0 } else { 0.75 };
    let header_id: SharedString = format!("thinking-hdr-{}-{}", msg_ix, block_ix).into();
    let viewer_state = thinking.state.clone();
    let viewer_title = title.clone();

    v_flex()
        .id(format!("thinking-block-{msg_ix}-{block_ix}"))
        .w_full()
        .max_w(px(680.))
        .rounded_lg()
        .border_1()
        .border_color(border_color())
        .bg(file_chip_bg())
        .overflow_hidden()
        .child(
            h_flex()
                .id(header_id)
                .gap_2()
                .items_center()
                .px_3()
                .py_2()
                .cursor_pointer()
                .text_color(text_2())
                .hover(|this| this.bg(file_chip_hover_bg()).text_color(text_color()))
                .child(
                    Icon::new(if thinking.done {
                        IconName::CircleCheck
                    } else {
                        IconName::LoaderCircle
                    })
                    .size_3p5(),
                )
                .child(
                    div()
                        .flex_1()
                        .text_size(px(13.))
                        .font_weight(gpui::FontWeight::MEDIUM)
                        .child(title),
                )
                .when(!thinking.done, |this| {
                    this.child(
                        h_flex()
                            .gap_1()
                            .items_center()
                            .child(typing_dot())
                            .child(typing_dot())
                            .child(typing_dot()),
                    )
                })
                .child(
                    div()
                        .id(format!("thinking-open-{msg_ix}-{block_ix}"))
                        .size_6()
                        .rounded_md()
                        .flex()
                        .items_center()
                        .justify_center()
                        .text_color(text_3())
                        .hover(|this| this.bg(hover_bg()).text_color(text_color()))
                        .tooltip(|window, cx| {
                            Tooltip::new(crate::tr!("chat_view.open_thoughts")).build(window, cx)
                        })
                        .child(Icon::new(IconName::Maximize).size_3p5())
                        .on_click(cx.listener(move |this, _, window, cx| {
                            cx.stop_propagation();
                            this.open_thinking_viewer(
                                viewer_title.clone(),
                                viewer_state.clone(),
                                window,
                                cx,
                            );
                        })),
                )
                .child(
                    Icon::new(IconName::ChevronDown)
                        .size_3p5()
                        .rotate(gpui::percentage(chevron_rotation)),
                )
                .on_click(cx.listener(move |this, _, _, cx| {
                    this.toggle_thinking_expanded((msg_ix, block_ix), cx);
                })),
        )
        .when(expanded, |this| {
            this.child(
                div()
                    .w_full()
                    .min_h_0()
                    .max_h(px(if thinking.done { 520. } else { 340. }))
                    .overflow_y_scrollbar()
                    .child(
                        v_flex()
                            .w_full()
                            .min_h_0()
                            .px_3()
                            .pb_4()
                            .text_size(px(13.5))
                            .line_height(relative(1.55))
                            .text_color(text_2())
                            .child(TextView::new(&thinking.state).selectable(true))
                            .child(div().h_2().flex_none()),
                    ),
            )
        })
}

fn attachment_detail_parts(detail: &SharedString) -> Vec<String> {
    detail
        .as_ref()
        .split(" · ")
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

fn attachment_size_label(attachment: &ImageAttachment) -> Option<SharedString> {
    let parts = attachment_detail_parts(&attachment.detail);
    match parts.as_slice() {
        [kind, size, ..] => Some(format!("{kind} · {size}").into()),
        [single] => Some(single.clone().into()),
        _ => None,
    }
}

fn document_parse_label(attachment: &ImageAttachment) -> SharedString {
    if attachment.detail.as_ref().contains("Parsing") {
        crate::tr!("chat_view.parsing")
    } else if let Some(parsed_text) = &attachment.parsed_text {
        crate::tr!(
            "chat_view.parsed_chars",
            count = parsed_text.chars().count()
        )
    } else if attachment.parse_error.is_some() {
        crate::tr!("chat_view.parse_failed")
    } else {
        crate::tr!("chat_view.ready")
    }
}

fn document_ocr_label(attachment: &ImageAttachment) -> Option<SharedString> {
    attachment_detail_parts(&attachment.detail)
        .into_iter()
        .find(|part| part.starts_with("OCR "))
        .map(Into::into)
}

fn metadata_chip(label: impl Into<SharedString>, color: Hsla) -> impl IntoElement {
    div()
        .px_1p5()
        .py_0p5()
        .rounded_full()
        .bg(file_chip_bg())
        .border_1()
        .border_color(border_color())
        .text_size(px(10.))
        .text_color(color)
        .truncate()
        .child(label.into())
}

fn render_generated_image<T: ChatViewState>(
    msg_ix: usize,
    block_ix: usize,
    image: &GeneratedImage,
    highlighted: bool,
    cx: &mut Context<T>,
) -> impl IntoElement {
    let title = image.title.clone();
    let prompt = image.prompt.clone();
    let size_label = image.size.clone();
    let url = image.url.clone();
    let copy_label = prompt.clone();
    let image_id = format!("generated-image-{msg_ix}-{block_ix}");
    let preview = ImageAttachment {
        title: title.clone(),
        url: url.clone(),
        detail: size_label.clone(),
        path: None,
        parsed_text: None,
        parse_error: None,
    };
    let preview_for_body = preview.clone();
    let preview_for_action = preview.clone();

    v_flex()
        .id(image_id)
        .w_full()
        .max_w(px(520.))
        .rounded_xl()
        .overflow_hidden()
        .border_1()
        .border_color(border_color())
        .when(highlighted, |this| this.border_2().border_color(accent()))
        .bg(white_color())
        .shadow_sm()
        .child(
            div()
                .id(format!("generated-image-open-{msg_ix}-{block_ix}"))
                .w_full()
                .h(px(248.))
                .bg(file_chip_bg())
                .child(render_image_content(url.clone(), title.clone()))
                .cursor_pointer()
                .on_click(cx.listener(move |this, _, window, cx| {
                    this.open_image_viewer(preview_for_body.clone(), window, cx);
                })),
        )
        .child(
            v_flex().gap_1().p_3().child(
                h_flex()
                    .gap_2()
                    .items_center()
                    .justify_between()
                    .child(
                        v_flex()
                            .min_w_0()
                            .child(
                                div()
                                    .text_size(px(13.5))
                                    .font_weight(gpui::FontWeight::SEMIBOLD)
                                    .text_color(text_color())
                                    .truncate()
                                    .child(title),
                            )
                            .child(
                                div()
                                    .text_size(px(12.))
                                    .text_color(text_3())
                                    .child(size_label),
                            ),
                    )
                    .child(
                        h_flex()
                            .gap_1()
                            .flex_shrink_0()
                            .child(image_action(
                                format!("copy-generated-prompt-{msg_ix}-{block_ix}"),
                                IconName::Copy,
                                crate::tr!("chat_view.copy_prompt"),
                                move |_, window, cx| {
                                    window.push_notification(
                                        Notification::info(crate::tr!(
                                            "chat_view.prompt_copied",
                                            prompt = copy_label.to_string()
                                        )),
                                        cx,
                                    );
                                },
                                cx,
                            ))
                            .child(image_action(
                                format!("open-generated-image-{msg_ix}-{block_ix}"),
                                IconName::ExternalLink,
                                crate::tr!("chat_view.open_image"),
                                move |this, window, cx| {
                                    this.open_image_viewer(preview_for_action.clone(), window, cx);
                                },
                                cx,
                            )),
                    ),
            ),
        )
}

fn render_attachment_thumbnail<T: ChatViewState>(
    id: String,
    attachment: &ImageAttachment,
    width: gpui::Pixels,
    height: gpui::Pixels,
    highlighted: bool,
    cx: &mut Context<T>,
) -> impl IntoElement {
    let title = attachment.title.clone();
    let detail = attachment.detail.clone();
    let preview = attachment.clone();
    let local_path = attachment.path.clone();
    let open_id = format!("{id}-open");
    let size_label = attachment_size_label(attachment);

    if attachment.is_document() {
        return v_flex()
            .id(id)
            .w(width)
            .gap_1()
            .child(
                div()
                    .id(open_id)
                    .h(height)
                    .w_full()
                    .rounded_lg()
                    .overflow_hidden()
                    .border_1()
                    .border_color(border_color())
                    .when(highlighted, |this| this.border_2().border_color(accent()))
                    .bg(file_chip_bg())
                    .child(render_document_attachment_preview(attachment))
                    .when_some(local_path.clone(), |this, path| {
                        this.cursor_pointer()
                            .tooltip(|window, cx| {
                                Tooltip::new(crate::tr!("chat_view.show_in_folder"))
                                    .build(window, cx)
                            })
                            .on_click(cx.listener(move |this, _, window, cx| {
                                this.reveal_file(path.clone(), window, cx);
                            }))
                    }),
            )
            .child(
                h_flex().gap_1().items_center().min_w_0().child(
                    div()
                        .flex_1()
                        .min_w_0()
                        .truncate()
                        .text_size(px(11.5))
                        .text_color(text_2())
                        .child(title),
                ),
            )
            .child(
                div()
                    .text_size(px(11.))
                    .text_color(text_3())
                    .truncate()
                    .child(detail),
            )
            .child(
                h_flex()
                    .gap_1()
                    .min_w_0()
                    .child(metadata_chip(
                        document_parse_label(attachment),
                        if attachment.parse_error.is_some() {
                            text_3()
                        } else {
                            text_2()
                        },
                    ))
                    .when_some(document_ocr_label(attachment), |this, label| {
                        this.child(metadata_chip(label, text_3()))
                    }),
            );
    }

    v_flex()
        .id(id)
        .w(width)
        .gap_1()
        .child(
            div()
                .id(open_id)
                .h(height)
                .w_full()
                .rounded_lg()
                .overflow_hidden()
                .border_1()
                .border_color(border_color())
                .when(highlighted, |this| this.border_2().border_color(accent()))
                .bg(file_chip_bg())
                .child(render_attachment_image(attachment))
                .cursor_pointer()
                .tooltip(|window, cx| {
                    Tooltip::new(crate::tr!("chat_view.show_in_folder")).build(window, cx)
                })
                .when_some(local_path.clone(), |this, path| {
                    this.on_click(cx.listener(move |this, _, window, cx| {
                        this.reveal_file(path.clone(), window, cx);
                    }))
                })
                .when(local_path.is_none(), |this| {
                    this.tooltip(|window, cx| {
                        Tooltip::new(crate::tr!("chat_view.open_image")).build(window, cx)
                    })
                    .on_click(cx.listener(move |this, _, window, cx| {
                        this.open_image_viewer(preview.clone(), window, cx);
                    }))
                }),
        )
        .child(
            div()
                .text_size(px(11.5))
                .text_color(text_2())
                .truncate()
                .child(title),
        )
        .child(
            div()
                .text_size(px(11.))
                .text_color(text_3())
                .truncate()
                .child(detail),
        )
        .when_some(size_label, |this, label| {
            this.child(
                h_flex()
                    .gap_1()
                    .min_w_0()
                    .child(metadata_chip(label, text_3())),
            )
        })
}

fn image_action<T: ChatViewState>(
    id: String,
    icon: IconName,
    tooltip: SharedString,
    on_click: impl Fn(&mut T, &mut Window, &mut Context<T>) + 'static,
    cx: &mut Context<T>,
) -> impl IntoElement {
    div()
        .id(id)
        .size_7()
        .rounded_md()
        .flex()
        .items_center()
        .justify_center()
        .cursor_pointer()
        .text_color(text_2())
        .hover(|this| this.bg(hover_bg()).text_color(text_color()))
        .tooltip(move |window, cx| Tooltip::new(tooltip.clone()).build(window, cx))
        .child(Icon::new(icon).size_3p5())
        .on_click(cx.listener(move |this, _, window, cx| on_click(this, window, cx)))
}

pub(crate) fn render_image_content(url: SharedString, title: SharedString) -> AnyElement {
    render_image_content_fit(url, title, ObjectFit::Cover)
}

fn render_image_content_fit(
    url: SharedString,
    title: SharedString,
    object_fit: ObjectFit,
) -> AnyElement {
    if url.starts_with("mock://") {
        return mock_image_preview(url, title);
    }

    img(url.clone())
        .size_full()
        .object_fit(object_fit)
        .with_loading({
            let url = url.clone();
            let title = title.clone();
            move || mock_image_preview(url.clone(), title.clone())
        })
        .with_fallback({
            let url = url.clone();
            let title = title.clone();
            move || mock_image_preview(url.clone(), title.clone())
        })
        .into_any_element()
}

pub(crate) fn render_attachment_image(attachment: &ImageAttachment) -> AnyElement {
    render_attachment_image_fit(attachment, ObjectFit::Cover)
}

pub(crate) fn render_attachment_preview(attachment: &ImageAttachment) -> AnyElement {
    if attachment.is_document() {
        return render_document_attachment_preview(attachment).into_any_element();
    }

    render_attachment_image(attachment)
}

fn render_document_attachment_preview(attachment: &ImageAttachment) -> Div {
    let parsed = attachment.parsed_text.is_some();
    let parsing = attachment.detail.as_ref().contains("Parsing");
    let status = document_parse_label(attachment);
    let status_color = if parsed { text_2() } else { text_3() };

    v_flex()
        .size_full()
        .items_center()
        .justify_center()
        .gap_1p5()
        .px_2()
        .child(render_attachment_file_icon(attachment, px(34.)))
        .child(
            div()
                .max_w_full()
                .text_size(px(11.5))
                .text_color(text_2())
                .truncate()
                .child(attachment.title.clone()),
        )
        .child(
            h_flex()
                .max_w_full()
                .gap_1()
                .items_center()
                .child(
                    Icon::new(if parsing {
                        IconName::LoaderCircle
                    } else if parsed {
                        IconName::CircleCheck
                    } else {
                        IconName::TriangleAlert
                    })
                    .size_3()
                    .text_color(status_color),
                )
                .child(
                    div()
                        .min_w_0()
                        .text_size(px(11.))
                        .text_color(status_color)
                        .truncate()
                        .child(status),
                ),
        )
}

fn render_attachment_file_icon(attachment: &ImageAttachment, size: gpui::Pixels) -> AnyElement {
    if let Some(path) = attachment.path.as_deref()
        && let Some(icon) = crate::system_file::file_icon(path)
    {
        return img(icon)
            .size(size)
            .object_fit(ObjectFit::Contain)
            .into_any_element();
    }

    Icon::new(IconName::File).size(size).into_any_element()
}

pub(crate) fn render_attachment_image_fit(
    attachment: &ImageAttachment,
    object_fit: ObjectFit,
) -> AnyElement {
    if let Some(path) = attachment.path.clone() {
        return img(path)
            .size_full()
            .object_fit(object_fit)
            .with_loading({
                let url = attachment.url.clone();
                let title = attachment.title.clone();
                move || mock_image_preview(url.clone(), title.clone())
            })
            .with_fallback({
                let url = attachment.url.clone();
                let title = attachment.title.clone();
                move || mock_image_preview(url.clone(), title.clone())
            })
            .into_any_element();
    }

    render_image_content_fit(attachment.url.clone(), attachment.title.clone(), object_fit)
}

fn mock_image_preview(url: SharedString, title: SharedString) -> AnyElement {
    let seed = image_seed(url.as_ref()) ^ image_seed(title.as_ref());
    let palette = match seed % 3 {
        0 => (
            hsla(36.0 / 360.0, 0.35, 0.78, 1.0),
            hsla(214.0 / 360.0, 0.28, 0.34, 1.0),
            hsla(24.0 / 360.0, 0.42, 0.48, 1.0),
            hsla(48.0 / 360.0, 0.78, 0.66, 1.0),
            hsla(154.0 / 360.0, 0.34, 0.36, 1.0),
            hsla(4.0 / 360.0, 0.56, 0.60, 1.0),
        ),
        1 => (
            hsla(206.0 / 360.0, 0.24, 0.78, 1.0),
            hsla(232.0 / 360.0, 0.30, 0.30, 1.0),
            hsla(30.0 / 360.0, 0.30, 0.52, 1.0),
            hsla(42.0 / 360.0, 0.82, 0.64, 1.0),
            hsla(168.0 / 360.0, 0.36, 0.34, 1.0),
            hsla(346.0 / 360.0, 0.42, 0.62, 1.0),
        ),
        _ => (
            hsla(96.0 / 360.0, 0.18, 0.78, 1.0),
            hsla(205.0 / 360.0, 0.26, 0.28, 1.0),
            hsla(28.0 / 360.0, 0.36, 0.44, 1.0),
            hsla(50.0 / 360.0, 0.74, 0.62, 1.0),
            hsla(132.0 / 360.0, 0.32, 0.34, 1.0),
            hsla(14.0 / 360.0, 0.54, 0.58, 1.0),
        ),
    };
    let (wall, screen, desk, lamp, plant, accent_panel) = palette;
    let lamp_side = if seed % 2 == 0 { 0.12 } else { 0.18 };

    div()
        .size_full()
        .relative()
        .overflow_hidden()
        .bg(wall)
        .child(
            div()
                .absolute()
                .left_0()
                .right_0()
                .bottom_0()
                .h(relative(0.36))
                .bg(desk),
        )
        .child(
            div()
                .absolute()
                .left(relative(0.08))
                .top(relative(0.10))
                .w(relative(0.30))
                .h(relative(0.26))
                .rounded(px(6.))
                .bg(white_color().opacity(0.42))
                .border_1()
                .border_color(white_color().opacity(0.58)),
        )
        .child(
            div()
                .absolute()
                .right(relative(0.10))
                .top(relative(0.12))
                .w(relative(0.20))
                .h(relative(0.16))
                .rounded(px(5.))
                .bg(accent_panel.opacity(0.75)),
        )
        .child(
            div()
                .absolute()
                .left(relative(0.12))
                .bottom(relative(0.20))
                .w(relative(0.42))
                .h(relative(0.24))
                .rounded(px(8.))
                .bg(screen)
                .border_1()
                .border_color(white_color().opacity(0.32)),
        )
        .child(
            div()
                .absolute()
                .left(relative(0.18))
                .bottom(relative(0.16))
                .w(relative(0.30))
                .h(px(5.))
                .rounded_full()
                .bg(hsla(0.0, 0.0, 0.12, 1.0).opacity(0.55)),
        )
        .child(
            div()
                .absolute()
                .right(relative(lamp_side))
                .bottom(relative(0.24))
                .w(px(8.))
                .h(relative(0.26))
                .rounded_full()
                .bg(hsla(32.0 / 360.0, 0.30, 0.34, 1.0)),
        )
        .child(
            div()
                .absolute()
                .right(relative(lamp_side + 0.01))
                .bottom(relative(0.48))
                .w(relative(0.18))
                .h(relative(0.10))
                .rounded(px(12.))
                .bg(lamp),
        )
        .child(
            div()
                .absolute()
                .right(relative(lamp_side - 0.01))
                .bottom(relative(0.17))
                .w(relative(0.18))
                .h(px(7.))
                .rounded_full()
                .bg(hsla(32.0 / 360.0, 0.28, 0.30, 1.0)),
        )
        .child(
            div()
                .absolute()
                .right(relative(0.34))
                .bottom(relative(0.18))
                .w(relative(0.10))
                .h(relative(0.13))
                .rounded(px(5.))
                .bg(plant),
        )
        .child(
            div()
                .absolute()
                .right(relative(0.31))
                .bottom(relative(0.29))
                .w(relative(0.16))
                .h(relative(0.09))
                .rounded_full()
                .bg(plant.opacity(0.82)),
        )
        .into_any_element()
}

fn image_seed(text: &str) -> u64 {
    text.bytes().fold(0xcbf29ce484222325u64, |hash, byte| {
        hash.wrapping_mul(0x100000001b3) ^ u64::from(byte)
    })
}

fn render_tool_call<T: ChatViewState>(
    msg_ix: usize,
    tool_ix: usize,
    tool: &ToolCall,
    expanded: bool,
    highlighted_artifact: Option<ArtifactHighlightTarget>,
    cx: &mut Context<T>,
) -> Div {
    let header_id: SharedString = format!("tool-hdr-{}-{}", msg_ix, tool_ix).into();
    // `gpui::percentage()` requires 0..=1. Collapsed = 270° clockwise = 0.75.
    let chevron_rotation: f32 = if expanded { 0.0 } else { 0.75 };
    let header = h_flex()
        .id(header_id)
        .gap_1p5()
        .items_center()
        .py_1()
        .cursor_pointer()
        .text_size(px(13.5))
        .text_color(text_2())
        .hover(|h| h.text_color(text_color()))
        .child(div().child(tool.title.clone()))
        .child(
            Icon::new(IconName::ChevronDown)
                .size_3p5()
                .rotate(gpui::percentage(chevron_rotation)),
        )
        .on_click(cx.listener(move |this, _, _, cx| {
            let key = (msg_ix, tool_ix);
            this.toggle_tool_expanded(key, cx);
        }));

    let last_ix = tool.steps.len().saturating_sub(1);
    let timeline = v_flex().when(expanded, |col| {
        let steps = tool
            .steps
            .iter()
            .enumerate()
            .map(|(i, step)| {
                render_tool_step(
                    step,
                    msg_ix,
                    tool_ix,
                    i,
                    i == last_ix,
                    highlighted_artifact,
                    cx,
                )
            })
            .collect::<Vec<_>>();
        col.children(steps)
    });

    v_flex().w_full().child(header).child(timeline)
}

fn render_tool_step<T: ChatViewState>(
    step: &ToolStep,
    msg_ix: usize,
    tool_ix: usize,
    step_ix: usize,
    last: bool,
    highlighted_artifact: Option<ArtifactHighlightTarget>,
    cx: &mut Context<T>,
) -> Div {
    let line_color: Hsla = timeline_line();
    let chip_bg: Hsla = file_chip_bg();
    let chip_hover_bg: Hsla = file_chip_hover_bg();
    let icon_color = if step.done { accent() } else { text_3() };

    h_flex()
        .gap_0()
        .items_stretch()
        .child(
            v_flex()
                .w(px(28.))
                .items_center()
                .flex_shrink_0()
                .child(
                    div()
                        .size_5()
                        .flex()
                        .items_center()
                        .justify_center()
                        .text_color(icon_color)
                        .child(Icon::new(step.icon.clone()).size_4()),
                )
                .when(!last, |this| {
                    this.child(div().w(px(1.)).flex_1().min_h(px(12.)).bg(line_color))
                }),
        )
        .child(
            v_flex()
                .pl_2()
                .pt(px(2.))
                .pb_2()
                .gap_1p5()
                .flex_1()
                .min_w_0()
                .child(
                    div()
                        .text_size(px(13.5))
                        .text_color(if step.done { text_color() } else { text_2() })
                        .child(step.title.clone()),
                )
                .when_some(step.detail.clone(), |this, detail| {
                    this.child(
                        div()
                            .max_w(px(520.))
                            .text_size(px(12.))
                            .line_height(px(18.))
                            .text_color(text_3())
                            .child(detail),
                    )
                })
                .when_some(step.file_chip.clone(), |this, chip| {
                    let chip_label = chip.clone();
                    let chip_id = msg_ix * 1_000_000 + tool_ix * 1_000 + step_ix;
                    let highlighted = highlighted_artifact.is_some_and(|target| {
                        target.message_ix == msg_ix
                            && target.kind == ArtifactHighlightKind::ToolFile { tool_ix, step_ix }
                    });
                    this.child(
                        h_flex()
                            .id(("file-chip", chip_id))
                            .gap_1p5()
                            .items_center()
                            .px_2()
                            .py_0p5()
                            .rounded_md()
                            .border_1()
                            .border_color(if highlighted { accent() } else { chip_bg })
                            .when(highlighted, |this| this.border_2())
                            .bg(chip_bg)
                            .text_size(px(11.5))
                            .text_color(text_2())
                            .w(px(240.))
                            .cursor_pointer()
                            .hover(|h| h.bg(chip_hover_bg).text_color(text_color()))
                            .child(Icon::new(IconName::File).size_3())
                            .child(div().truncate().flex_1().child(chip))
                            .on_click(cx.listener(move |_, _, window, cx| {
                                window.push_notification(
                                    Notification::info(crate::tr!(
                                        "chat_view.opened",
                                        name = chip_label.to_string()
                                    )),
                                    cx,
                                );
                            })),
                    )
                }),
        )
}

fn render_thinking(mode: ChatMode) -> Div {
    div().child(
        v_flex()
            .items_start()
            .gap_2()
            .child(
                h_flex()
                    .gap_2()
                    .items_center()
                    .child(div().text_color(accent()).text_size(px(17.)).child("✳"))
                    .child(
                        div()
                            .text_size(px(12.))
                            .text_color(text_3())
                            .child(crate::tr!(
                                "chat_view.thinking_header",
                                mode = crate::i18n::chat_mode_label(mode).to_string()
                            )),
                    ),
            )
            .child(
                h_flex()
                    .gap_1p5()
                    .items_center()
                    .px_3p5()
                    .py_3()
                    .rounded_xl()
                    .rounded_bl(px(4.))
                    .bg(white_color())
                    .border_1()
                    .border_color(border_color())
                    .child(typing_dot())
                    .child(typing_dot())
                    .child(typing_dot()),
            ),
    )
}

fn typing_dot() -> Div {
    div().size(px(6.)).rounded_full().bg(hover_bg())
}
